contacts/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.contact, name="contact"),
]

pages/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^about/$', views.about, name="about"),
    url(r'^$', views.index, name="index"),   
]

projects/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.list, name="list"),
    url(r'details/(?P<slug>[\w-]+)/$', views.details, name="details"),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .sitemap import StaticViewSitemap, PortofoilioSitemap
from django.contrib.sitemaps.views import sitemap
sitemaps = {
    'static': StaticViewSitemap,
    'portofolio': PortofoilioSitemap
}

urlpatterns = [
    url(r'^', include('pages.urls', namespace='pages')),
    url(r'^portofolio/', include('projects.urls', namespace='projects')),
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),
    url(r'^admin/', admin.site.urls),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/models.py
from django.db import models

from datetime import datetime


class Contact(models.Model):
    project_name = models.CharField(max_length=256, blank=True, null=True)
    project_id = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=256)
    phone = models.CharField(max_length=256)
    email = models.EmailField(max_length=254)
    message = models.TextField(blank=True)
    contact_time = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return "{} | {}".format(self.name, self.email)

pages/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.utils.text import slugify
from django.shortcuts import reverse
from django.contrib.sitemaps import ping_google


class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=256)
    slug = models.SlugField(unique=True, blank=True)
    description = models.TextField(blank=True)
    url = models.URLField(max_length=256, blank=True)
    image = models.ImageField(upload_to='projects/%Y/%m/%d', blank=True)
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # Todo: check if the name already exists
        self.slug = slugify(self.name)
        super(Project, self).save(*args, **kwargs)
        try:
            ping_google()
        except Exception:
            pass

    def get_absolute_url(self):
        return reverse('projects:details', kwargs={'slug': self.slug})


class Screenshot(models.Model):

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='projects/%Y/%m/%d')


class Quote(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=254)
    phone = models.CharField(max_length=20, blank=True)
    message = models.TextField()

pages/forms.py
from django import forms
from django.core import validators


def is_not_empty(value):
    if value:
        raise forms.ValidationError("is not empty")


class ContactForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Name', 'class': 'form-control'}),
        max_length=256,
        error_messages={'required': 'Please, enter your name.'},
        label='')
    phone = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'phone', 'class': 'form-control'}),
        max_length=100,
        required=False,
        label='')
    email = forms.EmailField(widget=forms.TextInput(
        attrs={'placeholder': 'Email', 'class': 'form-control'}),
        error_messages={'required': 'Please, enter a valid email address.',
                        'invalid': 'Please enter a valid email address.'},
        label='')
    message = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'Message', 'class': 'form-control'}),
        error_messages={'required': 'Please, enter your message.'},
        label='')

    honeybot = forms.CharField(
        widget=forms.HiddenInput, required=False,
        label="Leave empty", validators=[is_not_empty])

contacts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from datetime import datetime
from django.core.mail import send_mail

from .models import Contact
from projects.models import Project


def contact(request):
    if request.method == "POST":
        # Get values
        project_name = request.POST.get('project_name', '')
        project_id = request.POST.get('project_id', '')
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        message = request.POST.get('message', '')
        Contact.objects.create(project_name=project_name,
                               project_id=project_id,
                               name=name,
                               email=email,
                               phone=phone,
                               message=message,
                               contact_time=datetime.now())

        send_mail("New Inquiry", "Receiving new inquiry for porject {}".format(
            project_name), (email,), ('minaeid90@gmail.com',))
        project_slug = str(Project.objects.filter(name=project_name)[0].slug)
    return redirect('projects:details', slug=project_slug)

pages/views.py
from django.shortcuts import render
from django.core.mail import send_mail, EmailMessage
from .forms import ContactForm


def index(request):
    return render(request, 'pages/index.html')


def about(request):
    return render(request, 'pages/about.html')


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            EmailMessage(
                subject='Contact Us: {}'.format(form.cleaned_data['name']),
                body=str(form.cleaned_data['message']),
                from_email='minaeid90@gmail.com',
                to=['minaeid90@gmail.com'],
                reply_to=[form.cleaned_data['email']],
            ).send()
        #     context['success'] = 'Your message was saved successfully! '
            form = ContactForm()
    else:
        form = ContactForm()
    context = {
        "form": form
    }
    return render(request, 'pages/contact.html', context)

projects/views.py
from django.shortcuts import render, get_object_or_404

from .models import Project, Screenshot


def list(request):
    projects = Project.objects.all()
    context = {
        'projects': projects
    }
    return render(request, 'projects/list.html', context)


def details(request, slug):
    # Get images of the product
    project = get_object_or_404(Project, slug=slug)
    screenshots = Screenshot.objects.filter(project_id=project.id)
    context = {
        "project": project,
        "screenshots": screenshots
    }
    return render(request, 'projects/details.html', context)

templates/base.html
{% load static %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon.ico' %}">
    <!-- SEO  -->
    <meta name="description" content="DigitalCraftware provides a wide range of web and IT solutions. We develop websites and web applications from idea to design, development and hosting." />
    <meta name="keywords" content="DigitalCraftware IT solutions websites web application design developement deployment hosting" />
    <meta name="google-site-verification" content="V2XVC3ACAaWRVe1ut7riXffFqc2Sh18OePDoE299QkQ" />

    <title>
    {% block title %}
      DigitalCraftware
    {% endblock title %}
      </title>
    <!-- favicon -->
   {% compress css %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/all.css' %} ">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Lightbox -->
    <link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}">
    <!-- Custom -->
    <link rel="stylesheet" href="{% static 'css/style.css' %} ">
    {% endcompress %}
  </head>
  <body>
    <!-- Top Bar -->
    <section id="top-bar" class="p-3">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <i class="fas fa-phone"></i> (+2) 0128-367-5510
          </div>
          <div class="col-md-4">
            <i class="fas fa-envelope-open"></i> info@digitalcraftware.com
          </div>
          <div class="col-md-4">
            <div class="social text-right">
              <!-- <a href="#">
                <i class="fab fa-twitter"></i>
              </a> -->
              <a href="https://www.facebook.com/DigitalCraftware-613053245819244/">
                <i class="fab fa-facebook"></i>
              </a>
              <a href="https://www.instagram.com/digitalcraftware/">
                <i class="fab fa-instagram"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    <!-- Navbar -->
    {% with request.resolver_match.url_name as url_name %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'pages:index' %}">
          <img src="{% static 'img/logo.png' %} " class="logo" alt="website logo" >
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <ul class="navbar-nav">
            <li class="nav-item mr-3 {% if url_name == 'index' %} active {% endif %}">
              <a class="nav-link" href="{% url 'pages:index' %}">Home</a>
            </li>
            <li class="nav-item mr-3 {% if url_name == 'about' %} active {% endif %}">
              <a class="nav-link" href="{% url 'pages:about' %}">About</a>
            </li>
            <li class="nav-item mr-3 {% if url_name == 'list' %} active {% endif %}">
              <a class="nav-link" href="{% url 'projects:list' %}">Portofolio</a>
            </li>
            <li class="nav-item mr-3 {% if url_name == 'contact' %} active {% endif %}">
              <a class="nav-link" href="{% url 'pages:contact' %}">Contact Us</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% endwith %}
    {% block content %} {% endblock content %}
    <!-- Footer -->
    <footer id="main-footer" class="py-4 bg-primary text-white text-center">
      Copyright &copy;
      <span class="year"></span> DigitalCraftware
    </footer>
    {% compress js %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}  "></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}  "></script>
    <script src="{% static 'js/lightbox.min.js' %}  "></script>
    <script src="{% static 'js/main.js' %}  "></script>
    {% endcompress %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
  
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-115928789-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() { dataLayer.push(arguments); }
      gtag('js', new Date());

      gtag('config', 'UA-115928789-2');
    </script>
   
  </body>
</html>

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ block.super }} - About Us
{% endblock title %}

{% block content %}
    <section id="showcase-inner" class="py-5 text-white">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h1 class="display-4">About Us</h1>
                    <p class="lead">Learn more about DigitalCraftware, our vision, mission and core values.</p>
                </div>
            </div>
        </div>
    </section>
    
    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'pages:index' %}">
                            <i class="fas fa-home"></i> Home</a>
                    </li>
                    <li class="breadcrumb-item active"> About</li>
                </ol>
            </nav>
        </div>
    </section>
    
    <section id="about" class="py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <!-- <h2>We Develope and </h2> -->
    
                    <img src="{% static 'img/about.jpg' %}" alt="about">
                    <p class="mt-4">Software company providing IT solutions. We provide web app development and ERP systems
                        satisfied customer requirements
                        through the latest stable and cutting-edge technologies.</p>
                </div>
    
            </div>
        </div>
    </section>
    
    <!-- Work -->
    <section id="work" class="bg-dark text-white text-center">
        <h2 class="display-4">Ready to get started?</h2>
        <h4>Ready to start a project or really curious about our process? Drop us a note or give us a call +2 01283675510;
            we’re
            happy to answer all your questions.</h4>
        <hr>
        <a href="{% url 'projects:list' %}" class="btn btn-secondary text-white btn-lg">Work With Us</a>
    </section>
    
    
    <section id="team" class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h4 class="display-4">Vision</h4>
                    <p>Our vision is to become a leading and key role player in the Egyptian technology industry, deliver
                        unique
                        and
                        competitive products.</p>
                </div>
    
                <div class="col-md-6">
                    <h4 class="display-4">Mission</h4>
                    <p>DigitalCraftware builds a unique portfolio for IT solutions competes in quality, innovation, and
                        cost.
                        Because the
                        product we sell is a service we inspire our customers with ideas and bring them into real
                        applications.</p>
                </div>
    
            </div>
    </section>
{% endblock content %}
    

templates/pages/contact.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }} - Contact Us
{% endblock title %}

{% block content %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">Contact Us</h1>
                <p class="lead">Got a question! We would love to hear from you.</p>
            </div>
        </div>
    </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'pages:index' %}">
                        <i class="fas fa-home"></i> Home</a>
                </li>
                <li class="breadcrumb-item active"> Contact us</li>
            </ol>
        </nav>
    </div>
</section>

<!-- CONTACT SECTION -->
<section id="contact" class="py-3">
    <div class="container">
        <div class="row">
            <!-- <div class="col-md-4">
                <div class="card p-4">
                    <div class="card-body">
                        <h4>Get In Touch</h4>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur, odio!</p>
                        <h4>Address</h4>
                        <p>550 Main st, Boston MA</p>
                        <h4>Email</h4>
                        <p>test@test.com</p>
                        <h4>Phone</h4>
                        <p>(555) 555-5555</p>
                    </div>
                </div>
            </div> -->
            <div class="col-md-8">
                <div class="card p-4">
                    <div class="card-body">
                        <h4 class="">Send us a message</h3>
                        <hr>
                        <form action="{% url 'pages:contact' %}" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <input class="btn btn-outline-primary btn-block " type="submit" value="Submit" />
                                    </div>
                                </div>            
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
    

templates/pages/index.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }} - Homepage
{% endblock title %}
    

{% block content %}
    <!-- Showcase -->
    <section id="showcase">
        <div class="overlay">
        <div class="container ">
            <div class="row align-items-center">
                <div class="col-9 p-5 mt-5">
                    <h1 class="display-3 font-weight-bold text-uppercase">Digital crafting from out to inside</h1>
                </div>
            </div>
        </div>
        </div>
    </section>
    
    
    
    <!-- <section id="services" class="py-5 bg-secondary text-white">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-4">
                    <i class="fas fa-comment fa-4x mr-4"></i>
                    <hr>
                    <h3>Consulting Services</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae,
                        provident iste consequatur
                        hic dignissimos ratione ea quae.</p>
                </div>
                <div class="col-md-4">
                    <i class="fas fa-home fa-4x mr-4"></i>
                    <hr>
                    <h3>Propery Management</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae,
                        provident iste consequatur
                        hic dignissimos ratione ea quae.</p>
                </div>
                <div class="col-md-4">
                    <i class="fas fa-suitcase fa-4x mr-4"></i>
                    <hr>
                    <h3>Renting & Selling</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae,
                        provident iste consequatur
                        hic dignissimos ratione ea quae.</p>
                </div>
            </div>
        </div>
    </section> -->

{% endblock content %}
    

templates/projects/details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {{ block.super }} - {{project.name | title}}
{% endblock title %}

{% block content %}
    <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'projects:list' %}">Portofolio</a>
          </li>
          <li class="breadcrumb-item active">{{project.name | title}}</li>
        </ol>
      </nav>
    </div>
  </section>
  
    
  <!-- Listing -->
  <section id="listing" class="py-4">
    <div class="container">
      <a href="{% url 'projects:list' %}" class="btn btn-light mb-4">Back To Portofolio</a>
      <div class="row">
        <div class="col-md-7">
          <!-- Home Main Image -->
          <img src="{{project.image.url}}" alt="" class="img-main img-fluid mb-3">
          <!-- Thumbnails -->
          <div class="row mb-5 thumbs">         
            <div class="row mb-5 thumbs">
              {% for thumb in screenshots %}
              <div class="col-md-2">
                <a href="{{thumb.image.url}}" data-lightbox="home-images">
                  <img src="{{thumb.image.url}}" alt="" class="img-fluid">
                </a>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="col-md-5">
          <div class="card mb-3">
            
            <div class="card-body">
              <h5 class="card-title">{{project.name | title}}</h5>
              <p class="text-primary">{{project.description}}<hp>
              <div>
                <a href="{{project.url}}" class="btn btn-outline-dark"><i class="fas fa-globe-americas"></i> Visit Site</a>
                <button class="btn btn-outline-dark" data-toggle="modal" data-target="#inquiryModal">Get Quote</button>
              </div>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  </section>

  <!-- Inquiry Modal -->
  <div class="modal fade" id="inquiryModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
          <button type="button" class="close" data-dismiss="modal">
            <span>&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="{% url 'contacts:contact' %}" method="POST">
            {% csrf_token %}
            
            <input type="hidden" name="project_id" value="{{project.id}}">
            <input type="hidden" name="project_name" class="form-control" value="{{project.name}}">
            <div class="form-group">
              <label for="name" class="col-form-label">Name:</label>
              <input type="text" name="name" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="email" class="col-form-label">Email:</label>
              <input type="email" name="email" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="phone" class="col-form-label">Phone:</label>
              <input type="text" name="phone" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="message" class="col-form-label">Message:</label>
              <textarea name="message" class="form-control"></textarea>
            </div>
            <hr>
            <input type="submit" value="Send" class="btn btn-block btn-secondary">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
    

templates/projects/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ block.super }} - Portofolio
{% endblock title %}

{% block content %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">Browse Our Portofolio</h1>
                <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
            </div>
        </div>
    </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'pages:index' %}">
                        <i class="fas fa-home"></i> Home</a>
                </li>
                <li class="breadcrumb-item active"> Portofolio</li>
            </ol>
        </nav>
    </div>
</section>

<section id="listings" class="py-4">
    <div class="container">
        <div class="row">
            {% for project in projects %}
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card listing-preview">
                        <img class="card-img-top" src="{{project.image.url}}" alt="" height="100" width="100">
                        <div class="card-img-overlay">
                            <!-- <h2>
                                <span class="badge badge-secondary text-white">$490,000</span>
                            </h2> -->
                        </div>
                        <div class="card-body">
                            <div class="listing-heading">
                                <h4 class="text-primary">{{project.name | upper }}</h4>
                                <p><i class="text-secondary"></i> {{project.category}}</p>
                            </div>
                            <hr>
                            <a href="{% url 'projects:details' project.slug %}" class="btn btn-primary btn-block">More Info</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
     
        </div>

        <!-- <div class="row">
                <div class="col-md-12">
                    <ul class="pagination">
                        {% if projects.has_other_pages %}
                            {% if projects.has_previous %}
                                <li class="page-item">
                                    <a href="?page={{projects.previous_page_number}}" class="page-link">
                                        <i>&laquo;</i>
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a href="#" class="page-link">
                                        <i>&laquo;</i>
                                    </a>
                                </li> 
                            {% endif %}
                            {% for i in projects.paginator.page_range %}                     
                                {% if i == projects.number %}
                                <li class="page-item active">
                                    <a href="?page={{i}}" class="page-link">{{i}}</a>
                                </li>
                                {% else %}
                                <li class="page-item">
                                    <a href="?page={{i}}" class="page-link">{{i}}</a>
                                </li>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        {% if projects.has_next %}
                        <li class="page-item">
                            <a href="?page={{projects.next_page_number}}" class="page-link">
                                <i>&raquo;</i>
                            </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a href="#" class="page-link">
                                <i>&raquo;</i>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div> -->
    </div>
</section>
{% endblock content %}
    
    